import { FC, JSX, useState, useEffect } from 'react';
import { Box, Typography, CircularProgress } from '@mui/material';
import { generateImage } from '../services/openaiService';

interface ImageGeneratorProps {
  prompt: string;
}

const ImageGenerator: FC<ImageGeneratorProps> = ({ prompt }): JSX.Element => {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetchImage = async () => {
      setLoading(true);
      setImageUrl(null); // Reset hình ảnh trước đó
      try {
        const url = await generateImage(prompt); // Gọi API để tạo ảnh
        setImageUrl(url as string); // Lưu URL ảnh
      } catch (error) {
        console.error(error);
        alert('Failed to generate image. Please try again.');
      } finally {
        setLoading(false); // Kết thúc trạng thái loading
      }
    };

    if (prompt) fetchImage();
  }, [prompt]);

  return (
    <Box mt={4} textAlign="center">
      {loading && (
        <Box display="flex" justifyContent="center" mt={2}>
          <CircularProgress />
        </Box>
      )}
      {imageUrl && (
        <Box mt={4}>
          <Typography variant="subtitle1" gutterBottom>
            Generated Image:
          </Typography>
          <img
            src={imageUrl}
            alt="Generated by AI"
            style={{
              width: '100%',
              maxWidth: '500px',
              borderRadius: '8px',
              boxShadow: '0 4px 8px rgba(0,0,0,0.2)',
            }}
          />
        </Box>
      )}
    </Box>
  );
};

export default ImageGenerator;
